# -*- coding: utf-8 -*-
#
# Copyright 2017-2018 - Swiss Data Science Center (SDSC)
# A partnership between École Polytechnique Fédérale de Lausanne (EPFL) and
# Eidgenössische Technische Hochschule Zürich (ETHZ).
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

sudo: required

notifications:
  email: false

services:
  - docker

env:
  global:
    - HELM_URL=https://storage.googleapis.com/kubernetes-helm
    - HELM_TGZ=helm-v2.8.2-linux-amd64.tar.gz
    - PLATFORM_VERSION=development 

git:
  depth: false

addons:
  hosts:
    - renga.build
    - gitlab.renga.build
    - jupyterhub.renga.build
    - keycloak.renga.build

branches:
  only:
    - master
    - development
    - test-chart-deployment

language: python

matrix:
  fast_finish: true

python:
  - "3.6"

before_install:
  - sudo apt-get install enchant shellcheck

install:
  - ./scripts/travis-install.sh

before_script: |-
    make start

script:
  - xvfb-run make test
  # TODO - helm lint charts/renga -f charts/minikube-values.yaml --set renga.domain=renga.build

before_deploy:
  # install chartpress
  - pip install -U pip
  - pip install -e git+https://github.com/jirikuncar/chartpress#egg=chartpress
  # install Helm
  - wget -q ${HELM_URL}/${HELM_TGZ}
  - tar xzfv ${HELM_TGZ}
  - PATH=`pwd`/linux-amd64/:$PATH
  - helm init --client-only
  # configure access to external services
  - openssl aes-256-cbc -K $encrypted_ba78b413d7f2_key -iv $encrypted_ba78b413d7f2_iv -in github_deploy_key.enc -out github_deploy_key -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
  - make login

deploy:
  - provider: script
    skip_cleanup: true
    script: >-
      cd charts;
      helm repo add renga https://swissdatasciencecenter.github.io/helm-charts/;
      helm dependency update renga;
      chartpress --commit-range "${TRAVIS_COMMIT_RANGE}" --push --publish-chart;
      git diff;
      cd ..
    on:
      branch: test-chart-deployment
